#!/bin/bash

source libs

M=(0 31 28 31 30 31 30 31 31 30 31 30 31)
year=$(date +%Y)
month=$(date +%m)
day=$(date +%d)
test "${month:0:1}" -eq 0 && month=${month#*0}
test "${day:0:1}" -eq 0 && day=${day#*0}

isYear $year && M[2]=29

mdays=${M[$month]}

week=$(date -d "$year-$month-01" +%u)

printf "%*s%s %d\n" 5 "" $(date +%B) $year
echo -e "一 二 三 四 五 \033[31;1m六 日\033[0m"

i=1
for row in {1..6} ; do
    for col in {1..7}; do
        if (($row == 1 && $col >= $week || $row != 1 && $i <= $mdays)); then
            if (($i == $day)) ; then
                printf "\033[40;37;1m%2d\033[0m " $i
            elif (($col >= 6)) ; then
                printf "\033[31;1m%2d\033[0m " $i
            else
                printf "%2d " $i
            fi
            let i++
        else
            printf "%2c " " "
        fi
    done
    echo
done
