#!/bin/bash


get_min_uid() {
    local uid_list=$(awk -F ":" '{print $3}' /etc/passwd)
    local uid=$(sed -nr 's/FIRST_UID=([0-9]+)/\1/p' /etc/adduser.conf)

    while true ; do
        egrep -q -w "$uid" <<< $uid_list && let uid++ || break
        # id $uid &> /dev/null && let uid++ || break
    done

    echo $uid
}

get_min_uid

