#!/bin/bash

read -p "请输入成绩: " num

if test $num -lt 0 -o $num -gt 100; then
    echo "请输入正确的成绩..."
    exit 1
fi

if [ $num -ge 90 ] ; then
    echo "A"
elif test $num -ge 80; then
    echo "B"
elif (( $num >= 70 )); then
    echo "C"
else
    echo "D"
fi


# if test $num -lt 0 -o $num -gt 100; then
    # echo "请输入正确的成绩..."
# else
    # if [ $num -ge 90 ] ; then
        # echo "A"
    # elif test $num -ge 80 -a $num -lt 90; then
        # echo "B"
    # elif (( $num >= 70 && $num < 80 )); then
        # echo "C"
    # else
        # echo "D"
    # fi
# fi

