#!/bin/bash

for i in hello 2 ls 4 5; do
    echo $i
done

echo "----------------------------------------------------"

for i in $(ls); do
    echo $i
done

echo "----------------------------------------------------"

for i in {1..10..2}; do
    echo $i
done

echo "----------------------------------------------------"

for i in $* ; do
    echo $i
done

for ((i = 0; i < 10; i++)) ; do
    echo $i
done
